swagger: '2.0'
info:
  title: XSS test
  description: |
    <img src="x" onerror="alert('XSS')"> <h1><font Color=red>Visit Our New WebSite </h1><h3><mark><a href="https://example.com" onclick="alert('XSS')">e x a m p l e.com</a><a href="https://example.com" onclick="alert('XSS')">e x a m p l e . c o m </a></mark></h3>
